favicon:
  enable: true
  icon: /images/purple-heart_1f49c.png
  touch_icon: /images/purple-heart_1f49c.png

avatar:
  author_photo: /images/icon-heart.png
  author_nickname: deopa0402
  path: /

gtag:
  enable: false
  gtagkey: UA-xxxxxxx-x

comments:
  enable: true

navbar:
  - name: Home
    enable: true
    path: /
    key: about
  - name: Archives
    enable: false
    path: /archives/
    key: archives
  - name: Categories
    enable: false
    path: /categories/
    key: categories
  - name: Tags
    enable: false
    path: /tags/
    key: tags
  - name: Friends
    enable: false
    path: /friends/
    key: friends
  - name: About
    enable: true
    path: /about/
    key: about

catalog:
  enable: true

# 버튼 여부
prevnext:
  enable: true

# 검색
search:
  enable: true
  placeholder:

#컬러 변경
colorSwitch:
  enable: true

#공유
postShare:
  enable: true

#코드 스타일
codeBlock:
  style: "mac-black"

  copy:
    enable: true

mathjax:
  enable: true

themeColor: "#B841F5"
